### ISSUE TITLE
Login silently fails

### ISSUE THREAD

**Issue by osiris-plus** [DoctorMcKay/node-steam-gameserver#3]
Hello.

Previously I was using this module and it was working perfectly. However, after catastrophic incident resulting in data loss, I no longer have my original script, so I had to rewrite it.

Now I've met with the issue that "server" does not login. No events fired, no errors, nothing.

```
const SteamGameServer = require("steam-gameserver");

const sv = new SteamGameServer();

sv.on("loggedOn", (details) => console.log(details));
sv.on("disconnected", (eresult, msg) => console.log(eresult, msg));
sv.on("error", (err) => console.error(err));

sv.logOn({
  appID: 4000,
  gameVersion: "2021.04.02",
  token: "XXXXXX",
});
```

What am I doing wrong?

**Comment by DoctorMcKay** [comment]
This module isn't really maintained, may I ask why you want to use this rather than [steam-user](https://github.com/DoctorMcKay/node-steam-user), which should be able to do everything this can?

**Comment by osiris-plus** [comment]
I need to log in with GSLT token to keep it up to date and prevent Steam from expiring it. I'm not seeing such functionality in steam-user.

**Comment by DoctorMcKay** [comment]
That exact code worked fine for me, using my own token.

**Comment by osiris-plus** [comment]
This is quite strange. It's not working for me no matter what platform or source IP I'm using. I've also tried cloning this repository instead of using npm package, still nothing.

**Comment by DoctorMcKay** [comment]
Try outputting debug logging:

```js
sv.on('debug', console.log);
```

**Comment by osiris-plus** [comment]
Still absolutely nothing in output.

**Comment by osiris-plus** [comment]
Seems like "connected" for CMClient never fires.

**Comment by osiris-plus** [comment]
Changing CMClient connection type to Steam.EConnectionProtocol.WebSocket worked. TCP and UDP do not work.

**Comment by osiris-plus** [comment]
Apparently Steam.EConnectionProtocol.TCP also works, I assumed it was the default type, but default one seems to be UDP.

**Comment by osiris-plus** [comment]
I don't even know anymore, it works for me without any manipulations on my end now.

**Comment by osiris-plus** [comment]
Seems like the problem was with cm_list.json / servers.json data not resolving properly. I copied these files from my home machine to remote linux server and it started working on that server too.

**Comment by osiris-plus** [comment]
Also npm package is outdated, so it doesn't come with up to date jsons.
